apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: flagger-loadtester-

commonLabels:
  service_name: flagger-loadtester
  service_type: flagger

namespace: flagger-loadtester-ns

resources:
  - service.yaml
  - deployment.yaml
  - namespace.yaml
  - ingress.yaml