namespace: flagger-system
commonLabels:
  service_name: flagger
resources:
  - namespace.yaml
  - account.yaml
  - rbac.yaml
  - crd.yaml
  - deployment.yaml
images:
  - name: ghcr.io/fluxcd/flagger
    newName: ghcr.io/fluxcd/flagger
    newTag: 1.38.0