apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  service_group: dev-app

bases:
- ../../../base/
- ../../../loadtester/

patchesStrategicMerge:
  - patch.yaml

patches:
- patch: |-
    - op: replace
      path: "/spec/rules/0/host"
      value: "flagger-loadtester.local"
  target:
    kind: Ingress
    name: flagger-loadtester-ing
    